spring:
  datasource:
    url: jdbc:postgresql://dpg-ci4i8jlph6eva346qek0-a.oregon-postgres.render.com:5432/db_postgres_api_produtos
    username: dbprodutos
    password: MZ1P5ZdRFk5uMgFULc10zy335SZov91y
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update